FFMPEG_CMD = 'ffmpeg'

## HUD GENERATION ##
GENERATION_CONFIG_ENV_PREFIX = 'hud_generation_config__'

## HUD TEMPLATES ##
TEXT_ELEMENT_TYPE = 'text'
FILEPATH_ELEMENT_TYPE = 'filepath'
FILENAME_ELEMENT_TYPE = 'filename'

TEMPLATE_ELEMENTS_TYPES = [TEXT_ELEMENT_TYPE]

OUTPUT_PATH_TEXT_ID = 'output_path'
